import Head from 'next/head';
import { Box, Button, Grid, Typography } from '@mui/material';
import DashboardLayout from '../components/Layout/DashboardLayout';
import SearchBar from '../components/SearchBar';
import { IoMdNotificationsOutline } from 'react-icons/io';
import { HiOutlineUser } from 'react-icons/hi';
import { MdOutlineEditNote } from 'react-icons/md';
import { TbBookmarks } from 'react-icons/tb';
import { AiOutlineEye, AiOutlinePlus } from 'react-icons/ai';
import CountCard from '../components/CountCard';
import ActivitiesCard from '@/components/RecentActivities/ActivitiesCard';
import ProjectsCard from '@/components/PostedProjects/ProjectsCard';
import { useState } from 'react';

export default function Home() {
  const [search, SetSearch] = useState('');
  return (
    <>
      <Head>
        <title>Reslink Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout>
        <Box
          px={6}
          py={4}
          sx={{
            backgroundColor: '#1F2129',
            color: '#FEFEFE',
            position: 'relative',
          }}
        >
          <Box display={'flex'} justifyContent={'space-between'}>
            <SearchBar
              placeholder={'Search'}
              value={search}
              onChange={(e) => SetSearch(e.target.value)}
            />
            <Box display={'flex'}>
              <IoMdNotificationsOutline
                style={{
                  fontSize: 24,
                  cursor: 'pointer',
                  marginTop: 6,
                  marginRight: 6,
                }}
              />
              <Button
                sx={{
                  backgroundColor: '#3FA268',
                  color: '#FEFEFE',
                  textTransform: 'capitalize',
                  borderRadius: '36px',
                  px: 2,
                  '&:hover': {
                    backgroundColor: '#3FA268',
                  },
                }}
              >
                <AiOutlinePlus style={{ marginRight: 4, fontSize: 16 }} />{' '}
                Create New Project
              </Button>
            </Box>
          </Box>
          <Box mt={6}>
            <Typography sx={{ fontSize: '30px' }}>
              Welcome Back, Olivia
            </Typography>
            <Typography color={'#F2F2F2'}>
              Track, manage researchers and submissions
            </Typography>
          </Box>
          <Grid container spacing={4} mt={0.5} mb={4} alignItems={'center'}>
            <Grid item xs={6} md={3}>
              {' '}
              <CountCard
                cardName={'Active Projects'}
                count={'07'}
                icon={
                  <HiOutlineUser
                    color="white"
                    fontSize={24}
                    style={{
                      backgroundColor: '#3FA268',
                      borderRadius: '50px',
                      padding: '10px',
                    }}
                  />
                }
              />
            </Grid>
            <Grid item xs={6} md={3}>
              {' '}
              <CountCard
                cardName={'Proposals'}
                count={'04'}
                icon={
                  <MdOutlineEditNote
                    color="white"
                    fontSize={24}
                    style={{
                      backgroundColor: '#3FA268',
                      borderRadius: '50px',
                      padding: '10px',
                    }}
                  />
                }
              />
            </Grid>

            <Grid item xs={6} md={3}>
              {' '}
              <CountCard
                cardName={'Active Jobs'}
                count={'03'}
                icon={
                  <TbBookmarks
                    color="white"
                    fontSize={24}
                    style={{
                      backgroundColor: '#3FA268',
                      borderRadius: '50px',
                      padding: '10px',
                    }}
                  />
                }
              />
            </Grid>

            <Grid item xs={6} md={3}>
              {' '}
              <CountCard
                cardName={'Applications'}
                count={'240'}
                icon={
                  <AiOutlineEye
                    color="white"
                    fontSize={24}
                    style={{
                      backgroundColor: '#3FA268',
                      borderRadius: '50px',
                      padding: '10px',
                    }}
                  />
                }
              />
            </Grid>
          </Grid>
          <Grid container spacing={2}>
            <Grid item xs={12} md={6}>
              <ProjectsCard />
            </Grid>
            <Grid item xs={12} md={6}>
              <ActivitiesCard />
            </Grid>
          </Grid>
          {/* Footer */}
          <Box
            sx={{
              mt: 3,
              pl: 5,
              py: 1,
              borderTop: '2px solid #475467',
              width: '100%',
            }}
          >
            <Typography fontSize={14} sx={{ opacity: '0.4', color: '#FEFEFE' }}>
              Copyright © 2023. Reslink. All rights reserved.
            </Typography>
          </Box>
        </Box>
      </DashboardLayout>
    </>
  );
}
